### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sholoomail** [X-Gorn/BulkLoader#2]
hi.
i upload a text file that contains these urls:
https://dl2.soft98.ir/soft/i/Internet.Download.Manager.6.38.Build.19.Portable.exe
https://dl2.soft98.ir/soft/i/Internet.Download.Manager.6.39.Build.2.CR.rar
https://dl2.soft98.ir/soft/i/Internet.Download.Manager.6.39.Build.2.Retail.exe

then i see this error (my bot log):

2021-08-26T06:36:36.023403+00:00 heroku[worker.1]: Starting process with command `python3 bot.py`
2021-08-26T06:36:36.626707+00:00 heroku[worker.1]: State changed from starting to up
2021-08-26T06:36:40.273258+00:00 app[worker.1]: Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
2021-08-26T06:36:40.273278+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-08-26T06:36:40.273279+00:00 app[worker.1]: 
2021-08-26T06:43:09.489785+00:00 app[worker.1]: unknown url type: ''
2021-08-26T06:43:09.489802+00:00 app[worker.1]: Traceback (most recent call last):
2021-08-26T06:43:09.489802+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
2021-08-26T06:43:09.489803+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2021-08-26T06:43:09.489803+00:00 app[worker.1]:   File "/app/bot.py", line 148, in loader
2021-08-26T06:43:09.489803+00:00 app[worker.1]:     download_file(url, dirs)
2021-08-26T06:43:09.489804+00:00 app[worker.1]:   File "/app/bot.py", line 100, in download_file
2021-08-26T06:43:09.489804+00:00 app[worker.1]:     dl = SmartDL(url, dl_path, progress_bar=False)
2021-08-26T06:43:09.489805+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pySmartDL/pySmartDL.py", line 136, in __init__
2021-08-26T06:43:09.489805+00:00 app[worker.1]:     if not utils.is_HTTPRange_supported(self.url, timeout=self.timeout):
2021-08-26T06:43:09.489806+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pySmartDL/utils.py", line 100, in is_HTTPRange_supported
2021-08-26T06:43:09.489807+00:00 app[worker.1]:     fullsize = get_filesize(url, timeout=timeout)
2021-08-26T06:43:09.489807+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pySmartDL/utils.py", line 127, in get_filesize
2021-08-26T06:43:09.489807+00:00 app[worker.1]:     urlObj = urllib.request.urlopen(url, timeout=timeout)
2021-08-26T06:43:09.489808+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 214, in urlopen
2021-08-26T06:43:09.489808+00:00 app[worker.1]:     return opener.open(url, data, timeout)
2021-08-26T06:43:09.489808+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 501, in open
2021-08-26T06:43:09.489809+00:00 app[worker.1]:     req = Request(fullurl, data)
2021-08-26T06:43:09.489809+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 320, in __init__
2021-08-26T06:43:09.489809+00:00 app[worker.1]:     self.full_url = url
2021-08-26T06:43:09.489810+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 346, in full_url
2021-08-26T06:43:09.489810+00:00 app[worker.1]:     self._parse()
2021-08-26T06:43:09.489810+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 375, in _parse
2021-08-26T06:43:09.489810+00:00 app[worker.1]:     raise ValueError("unknown url type: %r" % self.full_url)
2021-08-26T06:43:09.489811+00:00 app[worker.1]: ValueError: unknown url type: ''

**Comment by xgorn** [comment]
there's another line without any text, that's why it gave this error
